# Generated by Django 4.0.5 on 2022-07-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.FloatField(default=6000),
        ),
    ]
